# -*- coding: utf-8 -*-
VERSION_MAJOR: int = 0
VERSION_MINOR: int = 0
VERSION_PATCH: int = 5
VERSION_SUFFIX: str = ""

VERSION: str = f"{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}{VERSION_SUFFIX}"